### ISSUE TITLE
PagedFilterTable cannot be used, connector not found, why missing?

### ISSUE THREAD

**Issue by beihaifeiwu** [tepi/FilteringTable#106]

**Comment by beihaifeiwu** [comment]
![image](https://cloud.githubusercontent.com/assets/5372382/12445227/1048bbc4-bf9e-11e5-98c3-89229eeb8579.png)

**Comment by tepi** [comment]
Hi,

obviously the FilterTable is not present in your widgetset for some reason. Here's a few things to check:
1. Make sure you have compiled the widgetset after adding FT to the project
2. Make sure there was no compilation errors. With default settings the widgetset compiler only warns about the errors so it's easy to miss them. Please add -strict to the compilation command; this will make the compilation fail on error.

**Comment by beihaifeiwu** [comment]
Hi tepi, why I cannot use the released directly? Do I need to compile the project myself?

my dependency as follow:

```xml
    <dependency>
      <groupId>org.vaadin.addons</groupId>
      <artifactId>filteringtable</artifactId>
      <version>0.9.14.v7</version>
    </dependency>
```

**Comment by tepi** [comment]
Hi,

when using any Vaadin add-ons which contain client-side code, you always have to compile the widgetset for your specific project. More info and instructions are available at https://vaadin.com/directory/help/using-vaadin-add-ons

**Comment by beihaifeiwu** [comment]
Thanks for you anwser, I will try it now

**Comment by beihaifeiwu** [comment]
Hi tepi, I solved the problem by compile my own widetset, thank you very much!

**Comment by Abdelrahman-Hasan** [comment]
Hi all please i need solution for my issue
#105 
Thanls
