### ISSUE TITLE
Improve performances while getting Item properties in CustomTable.parseItemIdToCells

### ISSUE THREAD

**Issue by andrealuciano71** [tepi/FilteringTable#109]
Hi, I was testing performances of Filtering Table (filteringtable-0.9.15.v7) in combination with the Vaadin JPA Container.
I know JPA Container is not a good choice, but this test helped me to find a possible improvement in the add-on's code.
In CustomTable.java method parseItemIdToCells at line 2276, there is a loop on columns which calls getContainerProperty a lot of times:

```
for (int j = 0; j < cols; j++) {
...
  p = getContainerProperty(id, colids[j]);
...
```

This performs very badly with JPA Container, even if the Entity cached provider is employed.

Instead, if the enity item is gotten before the loop such as in the following example, then the performances are up to 300% better in my test:

```
Item item=getItem(id);
for (int j = 0; j < cols; j++) {
...
  // p = getContainerProperty(id, colids[j]);
  p = item.getItemProperty(colids[j]);
...
```

Regards,
[Source.zip](https://github.com/tepi/FilteringTable/files/224921/Source.zip)

Andrea

**Comment by tepi** [comment]
Not relevant anymore. The CustomTable class is no longer used.
