### ISSUE TITLE
Listener for filter event

### ISSUE THREAD

**Issue by fante76** [tepi/FilteringTable#116]
I think it would be interesting to add a listener on filter event fire, for example, to run the query on server side and bind filter to server. Some other frameworks gives this opportunity.

**Comment by tepi** [comment]
You can  already implement this either within a container implementation or in your own FilterGenerator implementation. I don't think a separate listener would provide much more value.

**Comment by fante76** [comment]
This ticket is 2 years old... I considered it as expired. Maybe you answer refers to new version. Anyway I don't use FilteringTable any longer.
