### ISSUE TITLE
WARNING: Tried to unregister TextField which is not registered

### ISSUE THREAD

**Issue by Tostino** [tepi/FilteringTable#117]
Hello, there is a lot of noise being generated by filter table by my application in the logs, because of $SUBJECT.

What causes this is having a hidden filter field for some of my columns (because it's unnecessary to filter on and causes confusion).

With this I get the warning, without I don't: table.setFilterFieldVisible("column", false);

**Comment by lordmikefin** [comment]
Hi,
I also get this same warning in one application, but not in older one.

App that shows this warning uses Vaadin 7.7.5 and FilteringTable 0.9.15.v7

The older app is still using Vaadin 6.8.17 and FilteringTable 0.9.0

**Comment by mvysny** [comment]
Maybe related to #87 ?

**Comment by tepi** [comment]
Fixed
