### ISSUE TITLE
VCustomScrollTable.sizeInit() contract violation

### ISSUE THREAD

**Issue by Fedoresko** [tepi/FilteringTable#119]
sizeInit() relies on table is attached. The comment reads: "Run only once when component is attached and received its initial content."
But it is called from FilterTableConnector's postLayout(). There is no guarentee that is is attached at this point and there is no check, so it simply just won't work ending up with zero sizes. Also it is not clear why sizeInit() is not called from onAttach() instead.

**Comment by tepi** [comment]
Not relevant anymore. The postLayout() -method no longer exists.
