### ISSUE TITLE
Filter bar zoom issue

### ISSUE THREAD

**Issue by Tostino** [tepi/FilteringTable#120]
I found a bug with FilteringTable which is pretty annoying for some of my users.
When zooming in/out when on chrome, the scrolling on tables acts very strange.

I took a video to explain much better than I could: https://www.opentest.co/share/f4648510dc3311e6a440733f650d916f

Pretty much, if you zoom to 110%, 80%, or 67% in Chrome, if there is a horizontal scroll bar, it'll start scrolling automatically to the left.  Other zoom levels don't do this. It also doesn't happen when using Edge / IE.

I figured out what is causing it, but I have no idea what the fix is because i'm terrible at CSS.

If the width below is not set, the issue above doesn't happen.  
.filters-panel {
	background-color: #D4D7D9;
	width: 90000px;
	overflow: hidden;
	height: 23px;
}

Obviously that is not a fix because that breaks the filter bar and makes it so scrolling doesn't work.

**Comment by tepi** [comment]
Closing as expired
