### ISSUE TITLE
Components set into container of FilterTable (1.0.1.v8) will cause errors.

### ISSUE THREAD

**Issue by lordmikefin** [tepi/FilteringTable#125]
First I want to thank you for this great addon.

But next let's get into my issue with it.

I'm migrating my V7 code to V8. But I have problems with FilterTable.

I made demo app to demonstrate the problem(s):
[My FilterTable demo](https://colosseum.grynos.com/Sandbox/?restartApplication#!Sandbox)

My demo is based on demo code:
[tepi's demo code](https://github.com/tepi/FilteringTable/blob/master/filteringtable-demo/src/main/java/org/tepi/filtertable/demo/FilterTableDemoUI.java)

Here is core code of my demo:
[filtertable_demo.zip](https://github.com/tepi/FilteringTable/files/1200427/filtertable_demo.zip)

NOTE: My app is still using 'reindeer' theme. Because of this I also had to do some CSS fixes. Otherwise filter bar was not visible. Here is my fix:
[filteringtable.scss.zip](https://github.com/tepi/FilteringTable/files/1200496/filteringtable.scss.zip)

In my demo app I have added tabs "Normal FilterTable with components" and "Normal Table with components".

Content of both tables should be same. But FilterTable has empty components in it ?!?!
If I collapse and uncollapse all columns, then components with content are drawn into the table.
Dose the widget have two different component for each component ???

When 'state' column is uncollapsed. I get these errors (in client side console): 
`Fri Aug 04 15:12:25 GMT+300 2017 com.vaadin.client.VConsole`
`SEVERE: Parent of connector ComboBoxConnector (154) is null. This is typically an indication of a broken component hierarchy`
`... ( NOTE: Ten of these. One for each row in the table. )`
`Fri Aug 04 15:12:25 GMT+300 2017 com.vaadin.client.VConsole
SEVERE: Parent of connector TextFieldConnector (254) is null. This is typically an indication of a broken component hierarchy`
`... ( NOTE: One of these. )`

If I select "Toggle Filter Bar visibility", then Filter bar contains "wrong" fields. And I get this error (in client side console):
`Fri Aug 04 15:48:56 GMT+300 2017 com.vaadin.client.communication.MessageHandler`
`SEVERE: Hierarchy claims that 256 is a child for 126 (org.tepi.filtertable.client.ui.FilterTableConnector) but no connector with id 256 has been registered. More information might be available in the server-side log if assertions are enabled`

By clicking "Reset" button I get "correct" filter fields.
NOTE: I have not implemented correct comparison methods for columns containing components.
So only "ID" and "validated" filters actually works. 

When I click a CheckBox within the table (and then somewhere else). I get this error (in server side console):
`Cause: java.lang.reflect.InvocationTargetException`
`Message: class com.grynos.erp.ErpUI: errorHandler > Unable to invoke method setChecked in com.vaadin.v7.shared.ui.checkbox.CheckBoxServerRpc`
`Link: (ErpUI.java:221)`
`com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method setChecked in com.vaadin.v7.shared.ui.checkbox.CheckBoxServerRpc`
`	...`
`Caused by: java.lang.reflect.InvocationTargetException`
`	...`
`Caused by: java.lang.NullPointerException`
`	... `

If I collapse and uncollape the 'checked' column, then CheckBoxs will not cause server side error ???

I hope this bug will be fixed soon. Otherwise I can't migrate to V8.

Thanks in advance.

**Comment by lordmikefin** [comment]
I debugged the code  :)
[Here is my code.](https://github.com/lordmikefin/FilteringTable)

Hopefully Teppo will merge my solution. Or improve on it :D

**Comment by nikkijuk** [comment]
WIth pair of height: inherited; (not supported by ie 11) and height: auto; (ie 11 supported definition) is css fix really useful and works at least with chrome, firefox and ie.
