### ISSUE TITLE
Trying to reorder columns and setting widths at the same only reorders columns. Width is change on the second call or when header is clicked

### ISSUE THREAD

**Issue by anasmi** [tepi/FilteringTable#126]
Steps to reproduce the issue:
(The name of columns is the same as in demo application. Tested with Vaadin 7.7.10. Issue doesn't present in table only)
1. Increase the width of column
2. Move column2 to the first place (so it's column2, column1, column3.
3. Press Reset. This will reorder the columns and set their widths to 100px as expected.
4. Increase the width of column2 again and move it to first place. Press Reset again.Pressing the button will restore the order but column2's width will not have changed.lick a column header for the size change to be actually applied.
5. Click the button to add some rows. This causes the table to have a vertical scrollbar.
6. Repeat steps 1 and 2 and press Reset. The width will successfully applied (because of the scrollbar, implicitly).

**Comment by anasmi** [comment]
[tableProblem.zip](https://github.com/tepi/FilteringTable/files/1224836/tableProblem.zip)

**Comment by anasmi** [comment]
Hi,
I have added yesterday accidentally the wrong example(it uses aregular Table, which works as expected)
This is the right one. Sorry for inconvenience

[tableProblem.zip](https://github.com/tepi/FilteringTable/files/1227441/tableProblem.zip)

**Comment by tepi** [comment]
Fixed. Please try out with the new 1.0.0.v7 release.
