### ISSUE TITLE
Implementing "NOT" filter

### ISSUE THREAD

**Issue by JavaTypica** [tepi/FilteringTable#130]
Hi Tepi,

I am trying to implement a client side NOT filter in my Vaadin application. I am assuming this should be done in FilterTable.java but couldn't even figure out the existing filter. Could you please direct me or tell me how and where to implement a "NOT" filter?

Thanks in advance!

JM

**Comment by tepi** [comment]
Provide your own implementation of FilterGenerator interface to your FilterTable. From there you can provide any Filter you want, based on the input the user did.
