### ISSUE TITLE
Published version 1.0.0.v7 missing fixes already present in earlier versions?

### ISSUE THREAD

**Issue by ocarmona** [tepi/FilteringTable#131]
Hi Tepi,

Having experienced an issue using the addon (latest version for Vaadin 7, 1.0.0.v7), to be exact this one: https://github.com/tepi/FilteringTable/issues/46. 

Supposed to be fixed , and version 0.9.15.v7 (latest one before 1.0.0.v7) contains the fix, but is not  there in v1.0.0.v7... I have seen similar reported issues, like this: https://github.com/tepi/FilteringTable/issues/127, about fixes existing in repo code but not in the published version...

It has been removed intentionally? Or there was some error publishing the latest version? Are you planning to re-publish a new version including this fixes?

PD: I tried to use 0.9.15v7 but it is missing some new functionality included in v1.0.0.v7

Thanks

**Comment by ritul3007** [comment]
We are also facing the same problem of the class cast exception due Custom Table changed to Table in the getSourceComponent method in the version
 v1.0.0.v7 it used to work in 0.9.15v7. We have updated as old version was having some other issue. We are using vaadin version 7.7.9 . Please fix this and provide if any work around can be done?

**Comment by tepi** [comment]
CustomTable has now been removed from V7 version as well, which should resolve this issue. Release will happen shortly.
