### ISSUE TITLE
PagedFilterTable setSizeFull

### ISSUE THREAD

**Issue by ghost** [tepi/FilteringTable#48]
Hi,

I want to use the PagedFilterTable. In my scenario the header- and filterrow as well as the control panel should be fixed. If the table content is to large to display all it should be scrollable. To achieve this I have to set the table to 'sizeFull'.

But when I browse through the pages of the table, the total amount of pages is calculated wrong as well as the interval of displayed rows.

The error occurs due to line 2891 - 2894 in CustomTable. Here the pageLength is set to amount of visiable columns in the UI.

To reproduce to bug the demo application can be used. Just change 'buildPagedTableTab' in FilterTableDemoUI to:

```
private Component buildPagedTableTab() {
  PagedFilterTable<IndexedContainer> pagedFilterTable = buildPagedFilterTable();
  pagedFilterTable.setSizeFull();

  final VerticalLayout mainLayout = new VerticalLayout();
  mainLayout.setSizeFull();
  mainLayout.setSpacing(true);
  mainLayout.setMargin(true);
  mainLayout.addComponent(pagedFilterTable);
  mainLayout.setExpandRatio( pagedFilterTable, 1);
  mainLayout.addComponent(pagedFilterTable.createControls());
  mainLayout.addComponent(buildButtons(pagedFilterTable));

  Panel p = new Panel();
  p.setStyleName( Reindeer.PANEL_LIGHT);
  p.setSizeFull();
  p.setContent( mainLayout);
  return p;
}
```

Regards, Dennis

**Comment by mamuf** [comment]
I have encountered this problem, too. In my opinion, the Paged* variant SHOULD NOT update the pageLength from the client at all. Let the component be scrollable, which is the default for large Vaadin components in smaller layouts anyway. Or is this against any Vaadin rules?

**Comment by tepi** [comment]
It's definitely not against any Vaadin rules. It's just that the Table component on which the FilteringTable is based on will do that (update pageLenght from client) by default - and I'm not sure it's a very simple task to disable that behavior. There could also be some side effects.

Of course, I haven't tried it. This is just my gut feeling.

**Comment by mamuf** [comment]
I think the biggest problem there is the Vaadin Table was built only with scrolling in mind because it's cool and who wants to click buttons to go through pages, right? Well our clients do :-). But that's of course to be discussed elsewhere. (Note that I did not study the new Grid component yet).

For now I am trying to modify the layouts so the table height in browser could not be changed and the scrolling (overflow) would be applied on some upper level of the component tree if needed.
