### ISSUE TITLE
Vaadin won't find the widgetset implementation

### ISSUE THREAD

**Issue by evacchi** [tepi/FilteringTable#54]
Hi, I cannot seem to be able to install the widgetset. I have added the dependency to ivy, recompiled my widgetset, annotated the UI class with @Widgetset, tried the same with web.xml, still Vaadin cannot seem to be able to find the widget. Are you able to tell me what am I doing wrong?

```
   Widgetset 'com.example.vaadintasktable.widgetset.VaadintasktableWidgetset' 
   does not contain implementation for org.tepi.filtertable.FilterTable. 
   Check its component connector's @Connect mapping, widgetsets GWT
   module description file and re-compile your widgetset. In case you have
   downloaded a vaadin add-on package, you might want to refer to add-on
   instructions.
```

**Comment by 23yue23** [comment]
> Hi, I cannot seem to be able to install the widgetset. I have added the dependency to ivy, recompiled my widgetset, annotated the UI class with @WidgetSet, tried the same with web.xml, still Vaadin cannot seem to be able to find the widget. Are you able to tell me what am I doing wrong?
> 
> ```
>    Widgetset 'com.example.vaadintasktable.widgetset.VaadintasktableWidgetset' 
>    does not contain implementation for org.tepi.filtertable.FilterTable. 
>    Check its component connector's @Connect mapping, widgetsets GWT
>    module description file and re-compile your widgetset. In case you have
>    downloaded a vaadin add-on package, you might want to refer to add-on
>    instructions.
> ```

Hello, how is your problem solved? If you have time, can you say it?
