### ISSUE TITLE
Avoiding copying of code

### ISSUE THREAD

**Issue by Nico-Przybylek** [tepi/FilteringTable#76]
I had a closer look on the source code and saw that for getting access to private members & methods you have duplicated the Vaadin table’s client and server code. Have you thought about adding the filters into the table header? Doing it that way will eliminate the needs to access the private methods & members. You won’t have to copy the VScrollTable and TableConnector classes anymore. Or do you see a problem with this approach? The HTML then looks like this:

<div class="v-table v-widget pagedtable v-table-pagedtable v-has-width v-has-height" style="width: 100%; height: 100%;">
    <div class="v-table-header-wrap v-filter-table-header-wrap" style="width: 1291px;">
        <div class="v-table-header v-filter-table-header" style="overflow: hidden;">
            <div style="width: 900000px;">
                <table>
                    <tbody>
                        <tr>
                            <td class="v-table-header-cell" style="width: 192px;">
                                <div class="v-table-resizer"></div>

```
                            <div class="v-table-sort-indicator"></div>
                            <div class="v-table-caption-container v-table-caption-container-align-left" style="width: 176px;">Header 1</div>
                        </td>
                        <td class="v-table-header-cell" style="width: 193px;">
                            <div class="v-table-resizer"></div>
                            <div class="v-table-sort-indicator"></div>
                            <div class="v-table-caption-container v-table-caption-container-align-left" style="width: 177px;">string2</div>
                        </td>
                    </tr>
                    <tr class="filters-panel">
                        <td class="v-table-header-cell">
                            <div class="filterwrapper" style="height: 23px; width: 193px;">
                                <input type="text" class="v-textfield v-widget v-textfield-prompt" tabindex="0" style="width: 193px;">
                            </div>
                        </td>
                        <td class="v-table-header-cell">
                            <div class="filterwrapper" style="height: 23px; width: 193px;">
                                <input type="text" class="v-textfield v-widget v-textfield-prompt" tabindex="0" style="width: 193px;">
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
```

...

In the server code Java Reflection and a super call in the iterator() method will allow to take out the duplicated code, too. 

By eliminating the copied Vaadin code updates to newer Versions of Vaadin should be easier.

**Comment by tepi** [comment]
This was finally implemented recently. Thanks for the idea and the source codes which enabled me to do this!
