### ISSUE TITLE
Filtering does not work on Generated Column

### ISSUE THREAD

**Issue by matthewsalbin** [tepi/FilteringTable#79]
Hello Tepi, 

Thanks again for this add-on.  Version 9.11.v7, however, does not provide correct filtering on a generated column.  The column generated is a string.  (Below, getPrimaryCommColGenerator() returns string data.)  When used with setFilterGenerator and setFilterDecorator, the filter shows but completely clears the data instead of providing the appropriate subset.  Also, the values/actions specified by isTextFilterImmediate() and getAllItemsVisibleString() of the Decorator are not honored.  

Code:

			contactsTable.setFilterBarVisible( true );
			contactsTable.addStyleName( "freetable" );
			contactsTable.setSizeFull();
			contactsTable.setContainerDataSource( model.getEndpointContactData() );
			contactsTable.addGeneratedColumn( "Primary Contact Method", getPrimaryCommColGenerator() );
			contactsTable.setFilterGenerator(new CustomFilterGenerator());
			contactsTable.setFilterDecorator(new CustomFilterDecorator());
			contactsTable.setVisibleColumns( "salutation", "name", "Primary Contact Method");
			contactsTable.setColumnHeader( "salutation", "Title" );
			contactsTable.setColumnHeader( "name", "Contact Name" );

In CustomFilterGenerator:

	private TextField pfmField;
	private TextField getPFM()
	{
		if (pfmField == null)
		{
			pfmField = new TextField();
			pfmField.setImmediate( true );
		}
		return pfmField;
	}
	
    @Override
    public AbstractField<?> getCustomFilterComponent(Object propertyId) {
        if (propertyId.equals("Primary Contact Method")) 
        {
        	return getPFM();
        }
        return null;
    }
	
In CustomFilterDecorator:

	@Override
	public boolean isTextFilterImmediate(Object propertyId) {
		return true;
	}

	@Override
	public String getAllItemsVisibleString() {
		return "All";
	}

**Comment by tepi** [comment]
Filtering happens in the container, but generated columns are only in the table - the container knows nothing about them.

If you're at least on Vaadin 7.4.0, try using the com.vaadin.data.util.GeneratedPropertyContainer.
