### ISSUE TITLE
NumberFilterPopup caption has less than symbol but should be greater than symbol

### ISSUE THREAD

**Issue by deckerra** [tepi/FilteringTable#84]
On line 188 v0.9.11.v7 of NumberFilterPopup:
```
content.setCaption(interval.getGreaterThanValue() + " < "
                        + valueMarker + " < " + interval.getLessThanValue());
```
should be
```
content.setCaption(interval.getGreaterThanValue() + " > "
                        + valueMarker + " < " + interval.getLessThanValue());
```

**Comment by tepi** [comment]
Hi,

I think the logic is correct:
1. Open NumberFilterPopup
2. Input 10 in the first field (greater than)
3. Input 20 in the second field (less than)
4. Caption will be "10 < [x] < 20" which means that the value has to to be greater than 10 and less than 20 - and this was what was set in steps 2 and 3.
