### ISSUE TITLE
Sorted column width problem

### ISSUE THREAD

**Issue by appello-account** [tepi/FilteringTable#85]
First issue
If you have a sorted column on an empty filter table, the column width will shrink to a very small width.
The column header caption will not be properly visible or readable.

Second issue
If you add some content to the sorted column, the column width will be the length of the (longest) content. If the longest content is less wider than the column header caption, the column header caption will not be properly visible or readable.

Thanks in advance

First issue

![sorted_1](https://cloud.githubusercontent.com/assets/11570283/6749440/90c9328c-cef0-11e4-94d9-38e162487e1e.PNG)

Second issue

![sorted_2](https://cloud.githubusercontent.com/assets/11570283/6749446/a573889a-cef0-11e4-9c6c-172154057aea.PNG)

**Comment by tepi** [comment]
This is how the vaadin framework's Table component works. Not going to change that in an add-on.
