### ISSUE TITLE
x claims that FilterTable is its parent, but the parent does not acknowledge the parenthood.

### ISSUE THREAD

**Issue by mvysny** [tepi/FilteringTable#87]
Thank you for your excellent component, we have been using FilterTable for some time now. After upgrade to 0.9.11, the following messages were present in our log:

com.vaadin.ui.ConnectorTracker cleanConnectorMap
WARNING: cleanConnectorMap unregistered connector com.vaadin.ui.TextField(3361) (parent: FilterTable(3314)). This should have been done when the connector was detached.

When I have tried to enable asserts (-ea), ConnectionTracker.cleanConnectorMap() fails with an exception that "The connector hierarchy is corrupted. .. etc"; also, the following messages are present in the log:
"x claims that FilterTable is its parent, but the parent does not acknowledge the parenthood."

I believe this bug is caused by the FilterFieldGenerator.addFilterColumn() method which always sets the newly created filter field parent, yet FilterTable.iterator() provides the filter field only when filtersVisible is true, which is by default false.
My suggested fix is to change FilterFieldGenerator method to only set the parent when filtersVisible is true. Thanks!

**Comment by ilovkatie** [comment]
Same problem here. After 0.9.11 upgrade, every hidden filter cause:
WARNING: ... unregistered connector com.vaadin.ui... (parent: ...). This should have been done when the connector was detached.

Howerver im not sure what exacly is causing this bug. Im using FilterTable like this:

  final FilterTable logsTable = new FilterTable();
  logsTable.setImmediate(true);
  logsTable.setSelectable(true);
  logsTable.setWidth("100.0%");
  logsTable.setHeight("100.0%");
  logsTable.setFilterBarVisible(true);

  logsTable.setContainerDataSource(container);

  logsTable.setFilterFieldVisible(BUTTON_PROPERTY, false);
  logsTable.setFilterFieldVisible(DATE_PROPERTY, false);
  logsTable.setFilterFieldVisible(ID_PROPERTY, false);

And Warning apears for every hid filter (3 times in this case)

**Comment by TorstenKruse** [comment]
Same for me.

As there is still no solution available and we were already extending FilterTable we overwrite the iterator() method and include the not visible filter controls. Of course not great, but works.

**Comment by dyachera** [comment]
@TorstenKruse, do you mind sharing with me your code for the overwrite of iterator() you used?

**Comment by TorstenKruse** [comment]
In our class extending FilterTable:

    @Override
    public Iterator<Component> iterator() {

        final Set<Component> children = new HashSet<Component>();
        if (visibleComponents != null) {
            children.addAll(visibleComponents);
        }
        if (initialized && isFilterBarVisible()) {
            for (final Object key : getColumnIdToFilterMap().keySet()) {
                final Component filter = getColumnIdToFilterMap().get(key);
                if (equals(filter.getParent()) /* && filter.isVisible() */) {
                    children.add(filter);
                }
            }
        }
        return children.iterator();
      }

**Comment by tepi** [comment]
Fixed
