### ISSUE TITLE
Chrome: filter field width does not match column width (Vaadin 6)

### ISSUE THREAD

**Issue by rste79** [tepi/FilteringTable#89]
Hi!
We're using the current version (0.9.2) of FilterTable addon with Vaadin 6.8.14 and we have seen that using Chrome (version 43.0.2357.130) the filter field width is greater or equal than the column width.
In other browsers the table displays fine.
Furthermore, if we hit repeatedly F5 to refresh the page, the problem manifests itself intermittently.
After further investigation, we have seen that the problem is not present in the demo and that it affects only text fields (each field is 16px larger than the column header).

Thanks!
Ste

**Comment by Rafaesp** [comment]
I can reproduce this error in the demo. Just load the page and hit F5 until it happens.
Chrome version: Versión 44.0.2403.155 m
![image](https://cloud.githubusercontent.com/assets/437825/9382392/b38069d0-4740-11e5-9b77-64826f968fa6.png)

**Comment by Rafaesp** [comment]
Also, it seems that the input filter is always exactly 10 pixels wider than the column td.

**Comment by Rafaesp** [comment]
I can confirm this is a bug in Chrome and they solved it in last Chrome beta version (chrome canary). So I think we can just close this and wait until Google releases a new version.

**Comment by tepi** [comment]
Yes, there was quite a bad bug in Chrome which broke basically all Vaadin 6 applications. Hopefully we will get a new version with this issue fixed soon.

**Comment by scalaenthusiast** [comment]
Is there an associated bug for Vaadin 7 about this? We see "similar" column shifting like this but is also random and inconsitent widths. Using component in Vaadin 7. 

This bug appears for both Chrome and Firefox...

**Comment by AlphaJuliettOmega** [comment]
I get a similar looking fail when I have a HorizontalLayout with Label children and the parent has a PX width, to fix it then I had to set each child label to .setWidth("100%"); and they shrunk to the appropriate size.

Juuuust in case this helps Tepi :^)

**Comment by scalaenthusiast** [comment]
I will give this a try and see if it helps...
