### ISSUE TITLE
Vaadin client compilation fails using Vaadin 7.5.1

### ISSUE THREAD

**Issue by NITenyaw** [tepi/FilteringTable#90]
Compilation of the Vaadin Widgetset fails if Vaadin 7.5.1 is used, due to a change of the return-value datatype of Vaadin's MeasuredSize .getInnerHeight()-method (was prior to 7.5.1: int; is: double). This method is called in "VFilterTable" on line 182.

Client compiler's error message:
Tracing compile failure path for type 'org.tepi.filtertable.gwt.client.ui.VFilterTable'
       [ERROR] Errors in 'jar:file:[...]/m2/repository/org/vaadin/addons/filteringtable/0.9.12.v7/filteringtable-0.9.12.v7.jar!/org/tepi/filtertable/gwt/client/ui/VFilterTable.java'
          [ERROR] Line 182: Type mismatch: cannot convert from double to int
    [ERROR] Aborting compile due to errors in some input files

**Comment by mvysny** [comment]
Thank you, the bug is resolved with the FilterTable 0.9.13.v7 release.
