### ISSUE TITLE
Filter syntax definition

### ISSUE THREAD

**Issue by hirro** [tepi/FilteringTable#98]
I have googled on this but didn't find anything. 

Is there any syntax for the string filters? Currently I want to match strings ending with ABC not all string containing that string.

Cheers!

**Comment by tepi** [comment]
FilteringTable uses Vaadin Filters. Please provide your own FilterGenerator to do the filtering the way you want to, and implement a new Filter if needed - or use one of Vaadin's existing filter implementations.
