### ISSUE TITLE
Vaadin 7.6.0 alpha

### ISSUE THREAD

**Issue by reggiepierce** [tepi/FilteringTable#99]
Widgetset compile fails here:

```
[INFO] Compiling module com.ipl.AppWidgetSet
[INFO]    Tracing compile failure path for type 'com.vaadin.client.ui.VCustomScrollTable'
[INFO]       [ERROR] Errors in 'jar:file:/C:/Users/USER/.m2/repository/org/vaadin/addons/filteringtable/0.9.13.v7/filteringtable-0.9.13.v7.jar!/com/vaadin/client/ui/VCustomScrollTable.java'
[INFO]          [ERROR] Line 2604: The method hasActiveRequest() is undefined for the type ApplicationConnection
[INFO]    [ERROR] Aborting compile due to errors in some input files
```

It looks like ApplicationConnection no longer has a public method for checking active requests.

**Comment by reggiepierce** [comment]
This is the nasty work around I came up with for now:

,,,
		// nasty hack
		protected boolean hasActiveRequest() {
			return !client.getMessageHandler().isInitialUidlHandled()
					|| isWorkPending()
					|| client.getMessageSender().hasActiveRequest();
		}

		@Override
		public void run() {
			if (hasActiveRequest() || navKeyDown) {
,,,

**Comment by zinou6987** [comment]
Hello,
I have the same issue with the plugin and Vaadin 7.6.0.
How do you do this hack?

Thank you

**Comment by danmattsson** [comment]
@reggiepierce, I'm having the same problem but can't see where I could apply the fix you describe above, I'd really appreciate if you could elaborate.

Thanks!

**Comment by reggiepierce** [comment]
Hi, in order to apply the fix, you must build the jar from scratch. The edit needs to be applied to VCustomScrollTable.class. From there you'll need to use maven to build the jar and then include it in your project's classpath.

I've hosted the changes I've made in a repository here: https://bitbucket.org/regbo/filteringtable

**Comment by bedinsky** [comment]
Hi reggiepierce,
thank you very much for your work!
I've checked out your repo at bitbucket but your project does not have a maven nature, it is eclipse ivy . Could you provide pom.xml ? or tell me where to start with maven, it is not very clear on vaadin site how to set up a maven project for addons

**Comment by zinou6987** [comment]
@reggiepierce thank you for this good work, it work for me too!

**Comment by reggiepierce** [comment]
Hey! There is no pom.xml, you will need to use ant to build with IVY.

Reading through some of these will help:
http://www.mkyong.com/tutorials/apache-ant-tutorial/

On Thu, Oct 22, 2015 at 5:12 AM, zinou6987 <notifications@github.com> wrote:

> @reggiepierce <https://github.com/reggiepierce> thank you for this good
> work, it work for me too!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tepi/FilteringTable/issues/99#issuecomment-150157082>.
>



-- 
Reginald Pierce
CEO
IP Lasso LLC
(484) 324-8115
reggie.pierce@iplasso.com
IPLasso.com
<https://IPLasso.com>

**Comment by ErikLundJensen** [comment]
Vaadin 7.6.0 is just around the corner (beta1 is available) is there any plan for releasing this add-on anytime soon?

**Comment by AydinChavez** [comment]
Can somebody pls upload the patched jar from Reggies repo, as long as there is no official fix?
Happy new year btw :)

**Comment by AydinChavez** [comment]
For those, who don't want to download and build the jar from reggies repository (which works with Vaadin 7.6) locally/manually, here is it:

[filteringtable-0.9.13.v0801.jar.zip](https://github.com/tepi/FilteringTable/files/76722/filteringtable-0.9.13.v0801.jar.zip)
